import type {Metadata} from 'next'
import "../globals.css";
import MainHeader from '@/components/MainHeader';
export const metadata: Metadata = {
  title: 'Daniel Arce - Blog',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-white text-white'>
        <MainHeader/>
        <main className="text-black">
        {children}
        </main>
      </body>
    </html>
  )
}
