import MainNav from "@/components/MainNav"
import "../globals.css";
export const metadata = {
  title: 'Daniel Campos Arce - Blog',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <MainNav/>
        <main>
        {children}
        </main>
      </body>
    </html>
  )
}
